version: "3.4"
services:
  zookeeper:
    image: bitnami/zookeeper
    container_name: zookeeper
    ports: 
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka
    container_name: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=host.docker.internal:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    ports: 
      - "9092:9092"
    depends_on:
      - zookeeper
    restart: on-failure
  kafka-topics-ui:
    image: obsidiandynamics/kafdrop
    container_name: kafka-ui
    environment:
    - KAFKA_BROKERCONNECT=kafka:9092
    ports:
    - "9000:9000"
    depends_on:
    - kafka